### ISSUE TITLE
assertSmallDataFrameEquality Scalatest bug

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/spark-fast-tests#64]
<img width="1280" alt="Screen Shot 2020-03-15 at 3 18 07 PM" src="https://user-images.githubusercontent.com/2722395/76709874-690e5880-66d0-11ea-9f74-e984f2c46407.png">

The `assertSmallDataFrameEquality` method always shows the first row as failing, even when it's the same.  It's also not adding the line break before printing the first row comparison line.

utest is properly outputting the first line so looks like this bug is only for Scalatest.

<img width="1178" alt="Screen Shot 2020-03-15 at 3 08 19 PM" src="https://user-images.githubusercontent.com/2722395/76709890-98bd6080-66d0-11ea-8607-316b1a355519.png">

Any suggestions on how to fix this?

**Comment by carlsverre** [comment]
I would print a color reset code as the first line followed by a newline and then the `actual/expected` message.  I think Scalatest is not handing the first color escape code as can be seen in it printing `[34m`.  Possibly it's due to that being followed by `[frank` which may make the printer consumed for some reason.

**Comment by MrPowers** [comment]
This should be fixed now.
